version: "2"
services:
    api:
        build: 
            context: .
            dockerfile: Dockerfile
        image: countries-api
        container_name: countries-api
        volumes:
          - ./target/gs-spring-boot-docker-0.1.0.jar app.jar
        ports:
          - "8080:8080"