version: "2"
services:
    api:
        build: 
            context: .
            dockerfile: Dockerfile
        image: countries-api
        container_name: countries-api
        volumes:
          - ./target/gs-spring-boot-docker-0.1.0.jar:/app.jar
        ports:
          - "8080:8080"
        links:
            - db
        depends_on:
            - db

    db:
        image: postgres
        container_name: countries-db
        ports:
            - "15432:5432"
        environment:
            - POSTGRES_DB=countries
